name: effects
description: Introduction to the effects API

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: "1.0.0-rc2"

flutter:
  assets:
    - assets/images/flame.png
